-- 0001_name_metadata.sql
--
-- Adds descriptive metadata to `babynames` so the app can:
--   * show a name's gender / origin / meaning behind the "+ info" button
--   * filter the matches page by gender and origin
--
-- This migration is deliberately ADDITIVE ONLY:
--   * `add column if not exists` never drops or rewrites existing data
--   * no view is created or replaced, so `v_random_names`, `v_swipes`,
--     `v_partners` and `v_matches` keep working exactly as they do today
--   * re-running it is safe (idempotent)
--
-- The app degrades gracefully when this has NOT been applied yet: the gender
-- and origin filters hide themselves and "+ info" says there is nothing to
-- show, so deploying the frontend before running this is fine.

alter table public.babynames
    add column if not exists gender  text,
    add column if not exists origin  text,
    add column if not exists meaning text;

comment on column public.babynames.gender  is 'Female | Male | Unisex - used by the matches page filter';
comment on column public.babynames.origin  is 'Etymological origin, e.g. Hebrew, Latin, Greek - used by the matches page filter';
comment on column public.babynames.meaning is 'Short human-readable meaning, shown behind "+ info" while swiping';

-- Backfill for the 200 seeded names. Matched on `name` rather than `id` so it
-- behaves the same in every environment regardless of insertion order.
update public.babynames as b
set gender  = v.gender,
    origin  = v.origin,
    meaning = v.meaning
from (values
    ('Olivia',      'Female', 'Latin',        'From the olive tree, a symbol of peace'),
    ('Emma',        'Female', 'Germanic',     'Whole, complete, universal'),
    ('Ava',         'Female', 'Latin',        'Bird, or life'),
    ('Sophia',      'Female', 'Greek',        'Wisdom'),
    ('Isabella',    'Female', 'Hebrew',       'Pledged to God'),
    ('Mia',         'Female', 'Italian',      'Mine, beloved'),
    ('Amelia',      'Female', 'Germanic',     'Work, industrious'),
    ('Harper',      'Female', 'English',      'Harp player'),
    ('Evelyn',      'Female', 'English',      'Wished for, desired'),
    ('Abigail',     'Female', 'Hebrew',       'My father is joy'),
    ('Emily',       'Female', 'Latin',        'Eager, striving'),
    ('Ella',        'Female', 'Germanic',     'All, completely; fairy maiden'),
    ('Elizabeth',   'Female', 'Hebrew',       'My God is an oath'),
    ('Camila',      'Female', 'Latin',        'Young ceremonial attendant'),
    ('Luna',        'Female', 'Latin',        'Moon'),
    ('Sofia',       'Female', 'Greek',        'Wisdom'),
    ('Avery',       'Female', 'English',      'Ruler of elves'),
    ('Mila',        'Female', 'Slavic',       'Gracious, dear'),
    ('Aria',        'Female', 'Italian',      'Air, melody'),
    ('Scarlett',    'Female', 'English',      'Bright red, cloth merchant'),
    ('Penelope',    'Female', 'Greek',        'Weaver'),
    ('Layla',       'Female', 'Arabic',       'Night'),
    ('Chloe',       'Female', 'Greek',        'Young green shoot'),
    ('Victoria',    'Female', 'Latin',        'Victory'),
    ('Madison',     'Female', 'English',      'Son of Maud'),
    ('Eleanor',     'Female', 'Greek',        'Bright, shining one'),
    ('Grace',       'Female', 'Latin',        'Grace, blessing'),
    ('Nora',        'Female', 'Irish',        'Honour, light'),
    ('Riley',       'Female', 'Irish',        'Valiant, courageous'),
    ('Zoey',        'Female', 'Greek',        'Life'),
    ('Hannah',      'Female', 'Hebrew',       'Favour, grace'),
    ('Hazel',       'Female', 'English',      'The hazel tree'),
    ('Lily',        'Female', 'Latin',        'The lily flower, purity'),
    ('Ellie',       'Female', 'Greek',        'Bright, shining one'),
    ('Violet',      'Female', 'Latin',        'The violet flower'),
    ('Lillian',     'Female', 'Latin',        'Lily'),
    ('Zoe',         'Female', 'Greek',        'Life'),
    ('Stella',      'Female', 'Latin',        'Star'),
    ('Aurora',      'Female', 'Latin',        'Dawn'),
    ('Natalie',     'Female', 'Latin',        'Born on Christmas Day'),
    ('Emilia',      'Female', 'Latin',        'Eager, striving'),
    ('Everly',      'Female', 'English',      'Wild boar meadow'),
    ('Leah',        'Female', 'Hebrew',       'Delicate, weary'),
    ('Aubrey',      'Female', 'Germanic',     'Elf ruler'),
    ('Willow',      'Female', 'English',      'The willow tree, graceful'),
    ('Addison',     'Female', 'English',      'Son of Adam'),
    ('Lucy',        'Female', 'Latin',        'Light'),
    ('Audrey',      'Female', 'English',      'Noble strength'),
    ('Bella',       'Female', 'Italian',      'Beautiful'),
    ('Nova',        'Female', 'Latin',        'New'),
    ('Brooklyn',    'Female', 'Dutch',        'Broken land, marshland'),
    ('Paisley',     'Female', 'Scottish',     'Church, place of worship'),
    ('Savannah',    'Female', 'Spanish',      'Treeless plain'),
    ('Claire',      'Female', 'Latin',        'Clear, bright'),
    ('Skylar',      'Female', 'Dutch',        'Scholar, sheltering'),
    ('Isla',        'Female', 'Scottish',     'The island'),
    ('Genesis',     'Female', 'Greek',        'Origin, beginning'),
    ('Naomi',       'Female', 'Hebrew',       'Pleasantness'),
    ('Elena',       'Female', 'Greek',        'Bright, shining light'),
    ('Caroline',    'Female', 'Germanic',     'Free woman, strong'),
    ('Eliana',      'Female', 'Hebrew',       'My God has answered'),
    ('Anna',        'Female', 'Hebrew',       'Grace, favour'),
    ('Maya',        'Female', 'Sanskrit',     'Illusion, dream'),
    ('Valentina',   'Female', 'Latin',        'Strong, healthy'),
    ('Ruby',        'Female', 'Latin',        'Deep red gemstone'),
    ('Kennedy',     'Female', 'Irish',        'Helmeted chief'),
    ('Ivy',         'Female', 'English',      'The ivy plant, faithfulness'),
    ('Ariana',      'Female', 'Greek',        'Most holy'),
    ('Aaliyah',     'Female', 'Arabic',       'Exalted, sublime'),
    ('Cora',        'Female', 'Greek',        'Maiden'),
    ('Madelyn',     'Female', 'Hebrew',       'Of Magdala, tower'),
    ('Alice',       'Female', 'Germanic',     'Noble'),
    ('Kinsley',     'Female', 'English',      'The king''s meadow'),
    ('Hailey',      'Female', 'English',      'Hay clearing'),
    ('Gabriella',   'Female', 'Hebrew',       'God is my strength'),
    ('Allison',     'Female', 'Germanic',     'Noble'),
    ('Gianna',      'Female', 'Italian',      'God is gracious'),
    ('Serenity',    'Female', 'Latin',        'Peaceful, untroubled'),
    ('Samantha',    'Female', 'Hebrew',       'Told by God'),
    ('Sarah',       'Female', 'Hebrew',       'Princess'),
    ('Autumn',      'Female', 'Latin',        'The harvest season'),
    ('Quinn',       'Female', 'Irish',        'Descendant of Conn, wisdom'),
    ('Eva',         'Female', 'Hebrew',       'Life'),
    ('Piper',       'Female', 'English',      'Pipe player'),
    ('Sophie',      'Female', 'Greek',        'Wisdom'),
    ('Sadie',       'Female', 'Hebrew',       'Princess'),
    ('Delilah',     'Female', 'Hebrew',       'Delicate'),
    ('Josephine',   'Female', 'Hebrew',       'God will add'),
    ('Nevaeh',      'Female', 'English',      'Heaven, spelled backwards'),
    ('Adeline',     'Female', 'Germanic',     'Noble'),
    ('Arya',        'Female', 'Sanskrit',     'Noble'),
    ('Emery',       'Female', 'Germanic',     'Brave, powerful'),
    ('Lydia',       'Female', 'Greek',        'From Lydia'),
    ('Clara',       'Female', 'Latin',        'Bright, clear'),
    ('Vivian',      'Female', 'Latin',        'Alive, lively'),
    ('Madeline',    'Female', 'Hebrew',       'Of Magdala, tower'),
    ('Peyton',      'Female', 'English',      'Fighting man''s estate'),
    ('Julia',       'Female', 'Latin',        'Youthful'),
    ('Rylee',       'Female', 'Irish',        'Valiant, courageous'),
    ('Liam',        'Male',   'Irish',        'Resolute protector'),
    ('Noah',        'Male',   'Hebrew',       'Rest, comfort'),
    ('Oliver',      'Male',   'Latin',        'Olive tree'),
    ('Elijah',      'Male',   'Hebrew',       'My God is the Lord'),
    ('James',       'Male',   'Hebrew',       'Supplanter'),
    ('William',     'Male',   'Germanic',     'Resolute protector'),
    ('Benjamin',    'Male',   'Hebrew',       'Son of the right hand'),
    ('Lucas',       'Male',   'Latin',        'Bringer of light'),
    ('Henry',       'Male',   'Germanic',     'Ruler of the home'),
    ('Theodore',    'Male',   'Greek',        'Gift of God'),
    ('Jack',        'Male',   'English',      'God is gracious'),
    ('Levi',        'Male',   'Hebrew',       'Joined, attached'),
    ('Alexander',   'Male',   'Greek',        'Defender of the people'),
    ('Jackson',     'Male',   'English',      'Son of Jack'),
    ('Mateo',       'Male',   'Spanish',      'Gift of God'),
    ('Daniel',      'Male',   'Hebrew',       'God is my judge'),
    ('Michael',     'Male',   'Hebrew',       'Who is like God?'),
    ('Mason',       'Male',   'English',      'Stoneworker'),
    ('Sebastian',   'Male',   'Greek',        'Venerable, revered'),
    ('Ethan',       'Male',   'Hebrew',       'Strong, enduring'),
    ('Logan',       'Male',   'Scottish',     'Little hollow'),
    ('Owen',        'Male',   'Welsh',        'Noble born, youthful'),
    ('Samuel',      'Male',   'Hebrew',       'God has heard'),
    ('Jacob',       'Male',   'Hebrew',       'Supplanter'),
    ('Asher',       'Male',   'Hebrew',       'Happy, blessed'),
    ('Aiden',       'Male',   'Irish',        'Little fire'),
    ('John',        'Male',   'Hebrew',       'God is gracious'),
    ('Joseph',      'Male',   'Hebrew',       'God will add'),
    ('Wyatt',       'Male',   'English',      'Brave in war'),
    ('David',       'Male',   'Hebrew',       'Beloved'),
    ('Leo',         'Male',   'Latin',        'Lion'),
    ('Luke',        'Male',   'Greek',        'Bringer of light'),
    ('Julian',      'Male',   'Latin',        'Youthful'),
    ('Hudson',      'Male',   'English',      'Son of Hudde'),
    ('Grayson',     'Male',   'English',      'Son of the steward'),
    ('Matthew',     'Male',   'Hebrew',       'Gift of God'),
    ('Ezra',        'Male',   'Hebrew',       'Help, helper'),
    ('Gabriel',     'Male',   'Hebrew',       'God is my strength'),
    ('Carter',      'Male',   'English',      'Cart driver'),
    ('Isaac',       'Male',   'Hebrew',       'He will laugh'),
    ('Jayden',      'Male',   'Hebrew',       'Thankful'),
    ('Luca',        'Male',   'Italian',      'Bringer of light'),
    ('Anthony',     'Male',   'Latin',        'Priceless, praiseworthy'),
    ('Dylan',       'Male',   'Welsh',        'Son of the sea'),
    ('Lincoln',     'Male',   'English',      'Lake colony'),
    ('Thomas',      'Male',   'Aramaic',      'Twin'),
    ('Maverick',    'Male',   'English',      'Independent, nonconformist'),
    ('Elias',       'Male',   'Hebrew',       'My God is the Lord'),
    ('Josiah',      'Male',   'Hebrew',       'The Lord supports'),
    ('Charles',     'Male',   'Germanic',     'Free man'),
    ('Caleb',       'Male',   'Hebrew',       'Wholehearted, devoted'),
    ('Christopher', 'Male',   'Greek',        'Bearer of Christ'),
    ('Ezekiel',     'Male',   'Hebrew',       'God strengthens'),
    ('Miles',       'Male',   'Latin',        'Soldier'),
    ('Jaxon',       'Male',   'English',      'Son of Jack'),
    ('Isaiah',      'Male',   'Hebrew',       'The Lord is salvation'),
    ('Andrew',      'Male',   'Greek',        'Strong, manly'),
    ('Joshua',      'Male',   'Hebrew',       'The Lord is salvation'),
    ('Nathan',      'Male',   'Hebrew',       'He gave'),
    ('Nolan',       'Male',   'Irish',        'Champion, noble'),
    ('Adrian',      'Male',   'Latin',        'From Hadria'),
    ('Cameron',     'Male',   'Scottish',     'Crooked nose'),
    ('Santiago',    'Male',   'Spanish',      'Saint James'),
    ('Eli',         'Male',   'Hebrew',       'Ascended, high'),
    ('Aaron',       'Male',   'Hebrew',       'Exalted, mountain of strength'),
    ('Ryan',        'Male',   'Irish',        'Little king'),
    ('Angel',       'Male',   'Greek',        'Messenger'),
    ('Cooper',      'Male',   'English',      'Barrel maker'),
    ('Waylon',      'Male',   'English',      'Land by the road'),
    ('Easton',      'Male',   'English',      'East-facing settlement'),
    ('Kai',         'Male',   'Hawaiian',     'Sea'),
    ('Christian',   'Male',   'Latin',        'Follower of Christ'),
    ('Landon',      'Male',   'English',      'Long hill'),
    ('Colton',      'Male',   'English',      'Coal town'),
    ('Roman',       'Male',   'Latin',        'Citizen of Rome'),
    ('Axel',        'Male',   'Scandinavian', 'Father of peace'),
    ('Brooks',      'Male',   'English',      'Of the brook'),
    ('Jonathan',    'Male',   'Hebrew',       'Gift of God'),
    ('Robert',      'Male',   'Germanic',     'Bright fame'),
    ('Jameson',     'Male',   'English',      'Son of James'),
    ('Ian',         'Male',   'Scottish',     'God is gracious'),
    ('Everett',     'Male',   'Germanic',     'Brave as a wild boar'),
    ('Greyson',     'Male',   'English',      'Son of the steward'),
    ('Wesley',      'Male',   'English',      'Western meadow'),
    ('Jeremiah',    'Male',   'Hebrew',       'The Lord will exalt'),
    ('Hunter',      'Male',   'English',      'One who hunts'),
    ('Leonardo',    'Male',   'Germanic',     'Brave as a lion'),
    ('Jordan',      'Male',   'Hebrew',       'To flow down'),
    ('Jose',        'Male',   'Spanish',      'God will add'),
    ('Bennett',     'Male',   'Latin',        'Blessed'),
    ('Silas',       'Male',   'Latin',        'Of the forest'),
    ('Nicholas',    'Male',   'Greek',        'Victory of the people'),
    ('Parker',      'Male',   'English',      'Park keeper'),
    ('Beau',        'Male',   'French',       'Handsome'),
    ('Weston',      'Male',   'English',      'West settlement'),
    ('Austin',      'Male',   'Latin',        'Great, magnificent'),
    ('Connor',      'Male',   'Irish',        'Lover of hounds'),
    ('Carson',      'Male',   'Scottish',     'Son of the marsh dwellers'),
    ('Dominic',     'Male',   'Latin',        'Belonging to the Lord'),
    ('Xavier',      'Male',   'Basque',       'New house'),
    ('Jace',        'Male',   'Hebrew',       'The Lord is salvation')
) as v(name, gender, origin, meaning)
where b.name = v.name;

-- Helps the matches page, which filters on these two columns.
create index if not exists babynames_gender_origin_idx
    on public.babynames (gender, origin);
